contact_links:
  - name: Feedback & Feature Requests
    url: https://github.com/TwilightZebby/Wikicord/discussions/new/choose
    about: Have ideas for Wikicord? Post it in our Discussions tab!
  - name: Add App
    url: https://discord.com/oauth2/authorize?client_id=1352584114775003206
    about: Want to add Wikicord to your own Server or as a User App? Use this link here!
